- name: ping the server
  hosts: new_server #which server to ping
  become: yes #to run the tasks with root privileges
  #list of tasks to execute on the server
  tasks:
  - name: ping the server 
    ansible.builtin.ping:
  - name: check the connectivity to the server
    ansible.builtin.debug:
      msg: "Hello from the server"