- name: ping the server
  hosts: all #which server to ping
  #list of tasks to execute on the server
  tasks:
  - name: ping the server 
    ansible.builtin.ping:
  - name: check the connectivity to the server
    ansible.builtin.debug:
      msg: "Hello from the server"